import { useState } from 'react';

export const createGlobalCommands = (navigate, t, playMyVibe) => [
  // Функциональные команды (действия)
  {
    id: 'cmd_play_music',
    title: t(`commands.cmd_play_music.title`),
    description: t(`commands.cmd_play_music.description`),
    action: () => playMyVibe(), // вызываем метод play из контекста
    keywords: ['музыка', 'вайб'],
    group: 'global',
  },

  // Переходы на страницы
  {
    id: 'linkHome',
    title: t('commands.link_home.title'),
    description: t('commands.link_home.description'),
    action: () => navigate('/'),
    keywords: ['main', 'главная', 'посты'],
    group: 'global',
  },
  {
    id: 'linkMessenger',
    title: t('commands.link_messenger.title'),
    description: t('commands.link_messenger.description'),
    action: () => navigate('/messenger'),
    keywords: ['сообщения', 'мессенджер', 'тг'],
    group: 'global',
  },
  {
    id: 'linkMusic',
    title: t('commands.link_music.title'),
    description: t('commands.link_music.description'),
    action: () => navigate('/music'),
    keywords: ['музыка', 'music'],
    group: 'global',
  },
  {
    id: 'linkInventory',
    title: t('commands.link_inventory.title'),
    description: t('commands.link_inventory.description'),
    action: () => navigate('/economic/inventory'),
    keywords: ['паки', 'пачки', 'подарки', 'items', 'inventory'],
    group: 'global',
  },
  {
    id: 'linkLeaderboard',
    title: t('commands.link_leaderboard.title'),
    description: t('commands.link_leaderboard.description'),
    action: () => navigate('/leaderboard'),
    keywords: ['статы', 'stats', 'очки', 'баллы', 'доход'],
    group: 'global',
  },
  {
    id: 'linkBages',
    title: t('commands.link_bages.title'),
    description: t('commands.link_bages.description'),
    action: () => navigate('/badge-shop'),
    keywords: ['украшения', 'бейдж', 'badge', 'иконка', 'icon', 'статус'],
    group: 'global',
  },
  {
    id: 'link_marketplace',
    title: t('commands.link_marketplace.title'),
    description: t('commands.link_marketplace.description'),
    action: () => navigate('/marketplace'),
    keywords: ['паки', 'пачки', 'подарки', 'магазин'],
    group: 'global',
  },
  {
    id: 'link_usernames',
    title: t(`commands.link_usernames.title`),
    description: t(`commands.link_usernames.description`),
    action: () => navigate('/username-auction'),
    keywords: ['юзернейм', 'аукцион', 'баллы', 'доход'],
    group: 'global',
  },
  {
    id: 'link_packs',
    title: t(`commands.link_packs.title`),
    description: t(`commands.link_packs.description`),
    action: () => navigate('/economic/packs'),
    keywords: ['паки', 'пачки', 'подарки', 'items', 'inventory', 'крутки'],
    group: 'global',
  },
  {
    id: 'link_bugs',
    title: t(`commands.link_bugs.title`),
    description: t(`commands.link_bugs.description`),
    action: () => navigate('/bugs'),
    keywords: ['ошибки', 'элемент', 'репорт', 'бля', 'трекер'],
    group: 'global',
  },
  {
    id: 'link_api',
    title: t(`commands.link_api.title`),
    description: t(`commands.link_api.description`),
    action: () => navigate('/documentapi'),
    keywords: ['апи', 'инструкция', 'подключение', 'конект'],
    group: 'global',
  },
  {
    id: 'link_stickers',
    title: t(`commands.link_stickers.title`),
    description: t(`commands.link_stickers.description`),
    action: () => navigate('/inform/sticker'),
    keywords: ['стики', 'гифки', 'мессенджер', 'тг', 'стикеры'],
    group: 'global',
  },
  {
    id: 'link_about',
    title: t(`commands.link_about.title`),
    description: t(`commands.link_about.description`),
    action: () => navigate('/about'),
    keywords: ['это че'],
    group: 'global',
  },
  {
    id: 'link_settings',
    title: t(`commands.link_settings.title`),
    description: t(`commands.link_settings.description`),
    action: () => navigate('/settings'),
    keywords: [
      'настройки',
      'фон',
      'ава',
      'юзернейм',
      'бейдж',
      'подарки',
      'украшения',
      'профиль',
    ],
    group: 'global',
  },
  {
    id: 'link_profile',
    title: t('commands.link_profile.title'),
    description: t('commands.link_profile.description'),
    action: () => navigate('/profile'),
    keywords: ['профиль', 'profile', 'аккаунт'],
    group: 'global',
  },
  {
    id: 'link_logout',
    title: t('commands.link_logout.title'),
    description: t('commands.link_logout.description'),
    action: () => {
      window.location.href = '/logout';
    },
    keywords: ['выход', 'logout', 'signout'],
    group: 'global',
  },
];
