// NSFW Overlay component
export const createNSFWOverlay = (isMobile: boolean, onShowSensitive: () => void) => ({
  NSFWOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 2,
    borderRadius: 'var(--main-border-radius)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    p: isMobile ? 2 : 4,
    textAlign: 'center',
    overflow: 'hidden',
  },
  NSFWIconContainer: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    mb: isMobile ? 1 : 2,
  },
  NSFWButton: {
    borderRadius: 'var(--small-border-radius)',
    fontWeight: 500,
    mb: isMobile ? 1 : 2,
    background: '#5c5b5e',
    color: '#fff',
    boxShadow: `
    0 0 0 4px rgba(95, 95, 95, 0.06) inset,
    0 1.5px 16px 0 rgba(65, 65, 65, 0.18) inset`,
    fontSize: isMobile ? '0.75rem' : '0.85rem',
    px: isMobile ? 0.5 : 1,
    py: isMobile ? 0.25 : 0.5,
    onClick: onShowSensitive,
  },
  NSFWText: {
    color: '#bdbdbd',
    opacity: 0.7,
    mt: isMobile ? 1 : 2,
    fontSize: isMobile ? '0.75rem' : '0.9rem',
    wordBreak: 'break-word',
    maxWidth: '100%',
  },
}); 